bg_image:
  type: string
  default: default
  description: Background image url
bg_color:
  type: string
  default: default
  description: Background color code
bg_gradient_1:
  type: string
  default: "#FAFFD1"
  description: Background gradient color code 1
bg_gradient_2:
  type: string
  default: "#A1FFCE"
  description: Background gradient color code 2
login_subheader:
  type: string
  default: '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p> <p class="center-aligned-element"><iframe width="560" height="315" src="https://www.youtube.com/embed/DXUAyRRkI6k" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></p>'
  description: Banner sub-header text (allows HTML markup)
